### ISSUE TITLE
JSON Schemas for /record 3.0

### ISSUE THREAD

**Issue by nasainsbury** [ORCID/orcid-model#38]
Can you look at providing the orcid-model in the JSON format, similar to: https://github.com/ORCID/orcid-model/tree/master/src/main/resources/record_3.0.

This is probably a decent amount of work, so I'm happy to look into this and create a PR possibly?

This would help massively with creating TS interfaces.

**Comment by nasainsbury** [comment]
Nevermind, I'm closing the issue, found the swagger docs where it seems a lot clearer: https://pub.orcid.org/v3.0/#!/Development_Public_API_v3.0/viewRecordv3.

**Comment by Jason-Gush** [comment]
Hi Nathan, was about to point you to the swagger, but be aware that this isn't being updated, and there are a few places where the swagger is stale and/or will generate invalid messages.
We've fixed the parts that we're aware of here: https://github.com/Royal-Society-of-New-Zealand/NZ-ORCID-Hub/tree/master/orcid_api and are likely to keep current with model changes as this is a core part of our app.
